site_name: Learn Kubernetes
site_url: https://www.patashale.in/learn-kubernetes/
site_author: Patashale™
site_description: Learn everything about Kubernetes here at Patashale™.
repo_url: https://github.com/patashale/learn-kubernetes
repo_name: patashale/learn-kubernetes
theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary:  blue
      accent:  blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.tabs

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/patashale
      name: Patashale™ on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/patashale
      name: Patashale™ on GitHub
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@patashale
      name: Patashale™ on Mastodon
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@patashale
      name: Patashale™ on YouTube
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@learn-kubernetes
      name: Learn Kubernetes on YouTube

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - social:
      cards_layout_options:
        background_color: "#326CE5"

nav:
  - Home: index.md
  - Concepts: 
      Components: concepts/components.md
  - Compute: compute.md
  - Storage: storage.md
  - Networking: networking.md
  - Security: security.md
  - Customization: customization.md


copyright: Copyright &copy; 2023 Patashale™
